package cn.zhangqin56.common.enums;

public enum CalculateTypeEnum {
    ADD,
    SUBTRACT,
    MULTIPLY,
    MULTIPLY_UP,
    MULTIPLY_DOWN,
    MULTIPLY_CEILING,
    MULTIPLY_FLOOR,
    MULTIPLY_HALF_UP,
    MULTIPLY_HALF_DOWN,
    MULTIPLY_HALF_EVEN,
    MULTIPLY_UNNECESSARY,
    DIVIDE_UP,
    DIVIDE_DOWN,
    DIVIDE_CEILING,
    DIVIDE_FLOOR,
    DIVIDE_HALF_UP,
    DIVIDE_HALF_DOWN,
    DIVIDE_HALF_EVEN,
    DIVIDE_UNNECESSARY,
}
